kibalabs/nftoftheday

app/src/app.tsx, app/src/numberUtil.ts
This implementation does not display the previous total transaction count while the page is loading.
=> Feature: show loading transactions while the page is loading

app/src/app.tsx, app/src/components/highestPricedTokenTransferCard.tsx, app/src/components/mostTradedTokenTransferCard.tsx, app/src/components/nftCard.tsx, app/src/components/randomTokenTransferCard.tsx, app/src/components/sponsoredTokenCard.tsx
This sets error to false on change of date  and handles API error for all nft cards
=> Feature: Handle API errors on in NftCard

app/package-lock.json, app/package.json
This allows NftOfTheDay to use the latest version of ui-react
=> Feature: update ui-react to v0.9.4-next.1

api/notd/manager.py, app/package-lock.json, app/package.json, app/src/app.tsx
After updating the interface looks like this while loading.
=> Feature: update packages

app/package-lock.json, app/package.json
=> Feature: update ui-react version

app/src/components/errorCard.tsx, app/src/components/highestPricedTokenTransferCard.tsx, app/src/components/mostTradedTokenTransferCard.tsx, app/src/components/nftCard.tsx, app/src/components/randomTokenTransferCard.tsx, app/src/components/sponsoredTokenCard.tsx, app/src/theme.ts
I headed header4 and edited the font-size to 1.3 but it's default is underlined.
=> Fix: Add Error card component to display error message

app/src/client/resources.ts, app/src/components/nftCard.tsx
This doesn't display collection row if it's null
=> Feature: check collection

app/src/pages/CollectionPage/CollectionPage.tsx, app/src/theme.ts
Looks like this on a Tablet:
Like this on mobile:
=> KIBA-1312: Redesign collection page

app/src/pages/CollectionPage/CollectionPage.tsx
=> KIBA-1313: Redesign title

app/src/components/TruncateText.tsx, app/src/pages/CollectionPage/CollectionPage.tsx, app/src/theme.ts
=> KIBA-1314: Truncate description text on CollectionPage

app/src/components/MetricView.tsx, app/src/components/TokenCard.tsx, app/src/pages/CollectionPage/CollectionPage.tsx, app/src/theme.ts
=> KIBA-1316: Add token card

app/src/components/nftCard.tsx
Meebits address should always show as an image
=> KIBA-1346: Display meebit as Image

app/src/pages/CollectionPage/CollectionPage.tsx
=> KIBA-1317: Add recent sales

app/src/client/resources.ts, app/src/components/MetricView.tsx, app/src/pages/CollectionPage/CollectionPage.tsx, app/src/pages/TokenPage/TokenPage.tsx
=> KIBA-1356: add token attributes

app/src/client/client.ts, app/src/client/endpoints.ts, app/src/client/resources.ts, app/src/components/TokenCard.tsx, app/src/pages/CollectionPage/CollectionPage.tsx, app/src/pages/TokenPage/TokenPage.tsx
=> KIBA-1355: Hook CollectionPage  to recent sales api

app/src/client/client.ts, app/src/client/endpoints.ts, app/src/client/resources.ts, app/src/components/TokenSaleRow.tsx, app/src/pages/CollectionPage/CollectionPage.tsx, app/src/pages/TokenPage/TokenPage.tsx, app/src/theme.ts
=> KIBA-1357: Token sales history

app/src/pages/CollectionPage/CollectionPage.tsx
Display 'no recent sales' if collection recent sales is empty, 
fix horizontal scroll of recent sales
fix link to token page
=> Display 'no recent sales ' if collection recent sale is empty

app/src/components/CollectionView.tsx, app/src/components/highestPricedTokenTransferCard.tsx, app/src/components/mostTradedTokenTransferCard.tsx, app/src/components/nftCard.tsx, app/src/components/randomTokenTransferCard.tsx, app/src/components/sponsoredTokenCard.tsx
=> KIBA-1389: Update HomePage to point to Collection Page and Token Page

app/src/pages/TokenPage/TokenPage.tsx
=> Display no recent sales in token page if empty

app/src/app.tsx, app/src/client/client.ts, app/src/client/endpoints.ts, app/src/pages/TokenPage/TokenPage.tsx
=> KIBA-1415: Add refresh Button to token page

app/src/app.tsx, app/src/client/client.ts, app/src/client/endpoints.ts, app/src/pages/CollectionPage/CollectionPage.tsx
=> KIBA-1416: Add refresh button to collection Page

app/src/components/TokenSaleRow.tsx
Add transaction button to token sales row
=> KIBA-1417: Add transaction button to token sales

app/src/pages/TokenPage/TokenPage.tsx
=> KIBA-1447: Last price and date

app/src/client/client.ts, app/src/client/endpoints.ts, app/src/pages/TokenPage/TokenPage.tsx
=> KIBA-1475: use token transfer API on TokenPage

app/src/pages/CollectionPage/CollectionPage.tsx
=> Fix: section titles should not scroll horizontally on CollectionPage

app/src/components/TruncateText.tsx
=> KIBA-1495: only show read more button on CollectionPage when relevant + center align description text

app/src/components/TokenSaleRow.tsx, app/src/components/TruncateText.tsx, app/src/components/highestPricedTokenTransferCard.tsx, app/src/components/nftCard.tsx, app/src/components/randomTokenTransferCard.tsx, app/src/dateUtil.ts, app/src/pages/CollectionPage/CollectionPage.tsx, app/src/titleUtil.ts
=> Fix: correct layout of CollectionPage

app/src/pages/CollectionPage/CollectionPage.tsx
=> KIBA-1520: Update Twitter list's max-width in Collection Page

api/notd/api/api_v1.py, api/notd/api/endpoints_v1.py, api/notd/manager.py
```
Query Response
[
{
'registry_address': '0x81Ae0bE3A8044772D04F32398bac1E1B4B215aa8',
'token_id': '1004'
},
{
'registry_address': '0x0000000005756B5a03E751bD0280e3A55BC05B6E',
'token_id': '10003'
},
{
'registry_address': '0x0000000006bC8D9e5e9d436217B88De704a9F307',
'token_id': '1020847100762815390390123822295304634370'
},
{
'registry_address': '0x0000000000771A79D0Fc7F3B7FE270eB4498F20b',
'token_id': '10'
},
{
'registry_address': '0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D',
'token_id': '10'
},
{
'registry_address': '0x00000000c6B0cDd437d0db01e9785347AB0c0C00',
'token_id': '10'
},
{
'registry_address': '0x1dfe7Ca09e99d10835Bf73044a23B73Fc20623DF',
'token_id': '1000003'
},
{
'registry_address': '0xd774557b647330C91Bf44cfEAB205095f7E6c367',
'token_id': '10003'
},
{
'registry_address': …
```
=> KIBA-1713: Create Token Heroes Api
